In [21]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

# step-2 create DataSet

In [22]:
data = {
    "Outlook": ["Sunny", "Sunny", "Overcast", "Rain", "Rain", "Overcast"],
    "Humidity": ["High", "High", "High", "Normal", "Normal", "Normal"],
    "Wind": ["Weak", "Strong", "Weak", "Weak", "Strong", "Strong"],
    "Play": ["No", "No", "Yes", "Yes", "No", "Yes"]
}

df = pd.DataFrame(data)
print(df)

    Outlook Humidity    Wind Play
0     Sunny     High    Weak   No
1     Sunny     High  Strong   No
2  Overcast     High    Weak  Yes
3      Rain   Normal    Weak  Yes
4      Rain   Normal  Strong   No
5  Overcast   Normal  Strong  Yes

# Encode the data

In [23]:
le=LabelEncoder()
for col in df.columns:
    df[col]=le.fit_transform(df[col])
print("\n encoded data:\n",df)

 encoded data:
    Outlook  Humidity  Wind  Play
0        2         0     1     0
1        2         0     0     0
2        0         0     1     1
3        1         1     1     1
4        1         1     0     0
5        0         1     0     1

In [24]:
x=df.drop("Play", axis=1)
y=df["Play"]

In [25]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [26]:
x_train

   Outlook  Humidity  Wind
5        0         1     0
2        0         0     1
4        1         1     0
3        1         1     1

In [27]:
x_test

   Outlook  Humidity  Wind
0        2         0     1
1        2         0     0

In [28]:
model=DecisionTreeClassifier(criterion="entropy")
model.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [29]:
y_pred=model.predict(x_test)
print("Predictions:",y_pred)

Predictions: [1 0]

In [30]:
accuracy=accuracy_score(y_test,y_pred)
print("accuracy:",accuracy)

accuracy: 0.5

In [31]:
new_data=pd.DataFrame([[2,1,1]],columns=x.columns)
prediction=model.predict(new_data)
print("New Data Prediction:","Yes" if prediction[0]==1 else "No")

New Data Prediction: Yes

In [32]:
importances=model.feature_importances_
for  feature, importance in zip(x.columns, importances):
    print(f"{feature}:{importance:.3f}")

Outlook:0.616
Humidity:0.000
Wind:0.384

In [42]:
plt.figure(figsize=(12, 6))
plot_tree(
   model,
   feature_names = list(x.columns),
   class_names=["No","Yes"],
   filled=True
 )
plt.show()

InvalidParameterError: The 'decision_tree' parameter of plot_tree must be an instance of 'sklearn.tree._classes.DecisionTreeClassifier' or an instance of 'sklearn.tree._classes.DecisionTreeRegressor'. Got RandomForestClassifier(criterion='entropy', random_state=42) instead.

# Random Forest Classifier

In [34]:
from sklearn.ensemble import RandomForestClassifier

In [35]:
model=RandomForestClassifier(
    n_estimators=100,
    criterion="entropy",
    random_state=42

)
model.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', random_state=42)

In [36]:
y_pred=model.predict(x_test)
print("Predictions:",y_pred)

Predictions: [1 0]